version: 1.2
notebooks:
  - format: JUPYTER
    language: PYTHON
    path: /GWAS_initial_analysis_completed.ipynb
  - format: JUPYTER
    language: PYTHON
    path: /GWAS_initial_analysis_completed.ipynb
